### ISSUE TITLE
Can't install - OrbitServiceProvider.php syntax error

### ISSUE THREAD

**Issue by toby1kenobi** [ryangjchandler/orbit#118]
I thought I'd give this a try as it looks useful (to me!). Trying to add it to an existing Laravel project with:

`composer require ryangjchandler/orbit`

but it fails with:

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In OrbitServiceProvider.php line 31:

 syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

This is on Windows 10, PHP8.1

**Comment by toby1kenobi** [comment]
Ah, at least partially my mistake - I hadn't switched from php7 to 8 in the CLI. Having done that and run composer install on my project again (which went fine), trying to add orbit now gives:

```
  Problem 1
    - ryangjchandler/orbit[v1.1.0, ..., v1.1.3] require illuminate/console ^9.0 -> found illuminate/console[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires ryangjchandler/orbit ^1.1 -> satisfiable by ryangjchandler/orbit[v1.1.0, v1.1.1, v1.1.2, v1.1.3].
```

**Comment by ryangjchandler** [comment]
@toby1kenobi Are you using Laravel 9?

**Comment by toby1kenobi** [comment]
I am! 

Actually, I just tried creating a fresh Laravel project from scratch and I could add your code just fine - it must be something at my end. I did switch from PHP 7 to 8, I guess maybe something didn't go smoothly there.

**Comment by ryangjchandler** [comment]
@toby1kenobi Going to close this issue since it's a user problem, not a problem with the package.
