### ISSUE TITLE
Edge case when pluralizing a class name

### ISSUE THREAD

**Issue by jayan-blutui** [ryangjchandler/orbit#130]
Before I explain what's going on, I understand that this issue will probably never happen in almost all cases, but I thought I'd mention it in case its not worth creating a PR.

So I noticed the weirdest thing with the `getOrbitalName` method in the `Orbital` concern, when pluralizing a name like "APp" (obviously this should be "App", but why not 😉) it is converted into `a_pps` because of the order of the methods on the `Str` helper class.

**Current:**

```php
// Will output APp class as "a_pps"
return (string) Str::of(class_basename(static::class))->snake()->lower()->plural();
```

**Proposed change:**

```php
// Will output APp as "apps"
return (string) Str::of(class_basename(static::class))->lower()->snake()->plural();
```

In my opinion it makes sense to make the name lowercase first before applying any other changes to the actual value.

**Comment by ryangjchandler** [comment]
@jayan-blutui This would be considered a breaking change in the current version of Orbit, sadly. It would cause existing directories with the "incorrect" naming to stop being used.

**Comment by ryangjchandler** [comment]
Going to close this as it's quite an edge case and severe breaking change for existing code bases.
