### ISSUE TITLE
Feature request: Update Scout Search Index when files change.

### ISSUE THREAD

**Issue by alexanderhorner** [ryangjchandler/orbit#136]
Currently you have to import changes manually. Maybe call `->searchable()` manually when the sqlite cache changes?

**Comment by alexanderhorner** [comment]
https://laravel.com/docs/9.x/scout#indexing

**Comment by johncarter-** [comment]
I think that if you change the file manually, the next time the model is booted, the index update should occur. Does that happen?

I don't know how you can detect a file change without running the app and booting the model 🤔
