### ISSUE TITLE
Unable to create a post model

### ISSUE THREAD

**Issue by jamesdordoy** [ryangjchandler/orbit#155]
Hey Ryan,

I tried installing this package into a fresh Laravel 10 install and following your README, however when i try and save a Post model using ```::create``` or ```->save();```. a file is not created in the content folder and i get a 404.

Ive created an example repo here: [https://github.com/jamesdordoy/orbit](https://github.com/jamesdordoy/orbit) and tested it on another machine to make sure its still an issue.

**Comment by ryangjchandler** [comment]
Hey, can you try adding `$table->id()` to the schema and see if that fixes the issue.

**Comment by jamesdordoy** [comment]
Yep perfect mate 👍

Cheers!
