### ISSUE TITLE
laravel 10.x

### ISSUE THREAD

**Issue by bahramzade** [ryangjchandler/orbit#162]
composer require ryangjchandler/orbit
./composer.json has been updated
Running composer update ryangjchandler/orbit
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ryangjchandler/orbit[v0.1.0, ..., v0.5.0] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - ryangjchandler/orbit[v0.5.1, ..., v0.7.4] require illuminate/database ^8.0 -> found illuminate/database[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - ryangjchandler/orbit[v0.8.0, ..., v0.9.1] require illuminate/console ^8.0 -> found illuminate/console[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - ryangjchandler/orbit[v1.0.0, ..., v1.1.4] require illuminate/console ^9.0 -> found illuminate/console[v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - ryangjchandler/orbit[v1.2.0, ..., v1.2.1] require symfony/yaml ^6.0 -> found symfony/yaml[v6.0.0, ..., v6.4.3] but the package is fixed to v7.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires ryangjchandler/orbit * -> satisfiable by ryangjchandler/orbit[v0.1.0, ..., v0.9.1, v1.0.0, ..., v1.2.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require ryangjchandler/orbit:*" to figure out if any version is installable, or "composer require ryangjchandler/orbit:^2.1" if you know which you need.

**Comment by ryangjchandler** [comment]
You have another package in your project which is using `symfony/yaml:^7.0` or you're explicitly requiring that version. Orbit currently only works with ^6.0.
