### ISSUE TITLE
help

### ISSUE THREAD

**Issue by bahramzade** [ryangjchandler/orbit#166]
SQLSTATE[HY000]: General error: 1 table stars has no column named content
INSERT INTO
  "stars" (
    "content",
    "course_id",
    "created_at",
    "id",
    "ip",
    "updated_at"
  )

        $existingStar = \App\Models\Star::where('ip', request()->ip())->where('course_id', $course)->first();

        if ($existingStar === null) {
            \App\Models\Star::create([
                'ip' => request()->ip(),
                'course_id' => $course,
            ]);
            $this->resetPage();
        } else {
            $this->resetPage();
        }

**Comment by ryangjchandler** [comment]
Please share model information. Your code does not help me debug the issue at all.
