### ISSUE TITLE
Improve missing column support

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/orbit#25]
Currently, if you have some data in a file but the column doesn't exist in the schema, it will throw an exception. I think there's a better way of handling this, but will need to make sure that the performance overhead isn't massive.

**Comment by guushuizen** [comment]
Would you want to change the way it's handled currently? Or do you want to keep the exception? 

I can make some time free tomorrow to dive into the code and see if I can come up with something.

**Comment by ryangjchandler** [comment]
> Would you want to change the way it's handled currently? Or do you want to keep the exception?
> 
> I can make some time free tomorrow to dive into the code and see if I can come up with something.

I've already started working on this, but thanks for the offer!
