### ISSUE TITLE
Changing primary key results in unexpected behaviour

### ISSUE THREAD

**Issue by pxlrbt** [ryangjchandler/orbit#26]
Hey,
just played a little bit with your package. Either I don't understand the `getKeyName()` method or it doesn't work. When I use the example from the readme with `slug` the slug is set to an auto-incrementing ID instead of the value I pass. Is this intended? 
I'd expect to pass any value that is used to store the file then.

**Comment by ryangjchandler** [comment]
Hi @pxlrbt, thanks for opening this issue. You'll need to set `$incrementing` to `false` on your model.

**Comment by ryangjchandler** [comment]
I've updated the README with a note about this.

**Comment by pxlrbt** [comment]
> I've updated the README with a note about this.

Thanks. Was just about to submit a PR to the docs 😅
