### ISSUE TITLE
Manipulating markdown files directly breaks functionality

### ISSUE THREAD

**Issue by pxlrbt** [ryangjchandler/orbit#29]
I just played around with the markdown driver and it seems a bit fragile. When I modify a file directly or add another file to the folder I get an empty collection when running `Model::all()`. Neither reverting the changed nor deleting the sqlite database or the new file helps. Only when I removed all files and start over the driver starts working again.

No issues with the YAML and JSON driver.

**Comment by ryangjchandler** [comment]
Hi @pxlrbt, thanks for reporting this issue. I'll try and reproduce this tonight and get a patch release out.

**Comment by pxlrbt** [comment]
@ryangjchandler No hurry. Just playing around to see what works and what doesn't ;)

**Comment by ryangjchandler** [comment]
> @ryangjchandler No hurry. Just playing around to see what works and what doesn't ;)

Appreciate it!

**Comment by ryangjchandler** [comment]
Does the issue still exist on v0.5.x?

**Comment by pxlrbt** [comment]
> Does the issue still exist on v0.5.x?

Tested on v0.6.0 and just downgraded to v0.5.2 which is also not working. I'm testing in a tinker session on Arch Linux.

**Comment by pxlrbt** [comment]
Just figured out, that this is only an issue if I am not defining a content column.

**Comment by ryangjchandler** [comment]
> Just figured out, that this is only an issue if I am not defining a content column.

Ah okay. This is related to #28 then, at the moment the Markdown field writes the actual Markdown to a `content` column but this will be fixed soon.

I'll move that up the list and add it to the next patch release.

**Comment by pxlrbt** [comment]
> Ah okay. This is related to #28 then, at the moment the Markdown field writes the actual Markdown to a `content` column but this will be fixed soon.

I only saw #27 and didn't think that this was an issue as it was saving fine. Only loading from disk was affected. Now I also understand that SQL Exception I got on the first `Model::all()` query 🤦🏼‍♂️. It didn't fill the cache database as it was trying to fill the non-existing content column.

**Comment by ryangjchandler** [comment]
@pxlrbt Please upgrade to v0.6.1.
