### ISSUE TITLE
Support nested resources

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/orbit#42]
Currently, Orbit will only pick up on content in the top-level of the model directory. This means that nested structures aren't currently supported.

To be completely honest, I'm not sure on the best way to support this. It's going to be a tricky one to get right because of the following:

The filename used for content matches the primary key. If you have nested content, e.g. `content/posts/sponsors/hello-world.md` - how does you generate the primary key for this when creating? You would need to have some sort of hierarchy that you follow.

Say you had a `slug` prop as the primary key, the slug for this would technically be `sponsors/hello-world`, so to get the model you'd need to do `Post::find('sponsors/hello-world')`...

**Comment by ryangjchandler** [comment]
I'm going to CC @erickpatrick in here because I know one of his projects uses a nested file structure.

**Comment by erickpatrick** [comment]
Hi @ryangjchandler I'll work more on the project this weekend and will provide some feedback here afterwards.

**Comment by ryangjchandler** [comment]
I've made the decision to not support nested resources at this moment in time. It's another layer of complexity to Orbit that isn't really necessary at the moment, since a lot of the "nested" nature of blogs, content management can be managed using relationships instead.

Please feel free to open a discussion if you have any thoughts.
