### ISSUE TITLE
Implement an `orbit:fresh` command

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/orbit#50]
Suggestion from @stancl that would be similar to `migrate:fresh` - clear out the Orbit specific content directories.

**Comment by ryangjchandler** [comment]
Not sure about the implementation of this one just yet. I'm thinking the simplest approach is going to be clearing out the `content/` directory completely.

**Comment by stancl** [comment]
Yeah, my bash implementation just cleared `content/**/*.md`

```sh
(rm -f content/**/*.md || true) && art orbit:clear && art db:seed
```
