### ISSUE TITLE
Add a generator command

### ISSUE THREAD

**Issue by JustSteveKing** [ryangjchandler/orbit#65]
While it is useful to jump into tinker or tinkerwell and just `Post::create()` it would be cool if you could have an interactive CLI so you could:

```bash
php artisan orbit:generate ModelName
```

Which would then ask you to give a name/title depending on how the model is routed.

**Comment by ryangjchandler** [comment]
Interesting idea... I've got some things I want to do first but I'll keep this in mind.

**Comment by JustSteveKing** [comment]
I'm happy to attempt a PR 🙂

**Comment by ryangjchandler** [comment]
> I'm happy to attempt a PR 🙂

Go for it!
