### ISSUE TITLE
Add an 'disable' flag

### ISSUE THREAD

**Issue by rgasch** [ryangjchandler/orbit#66]
Would it be possible to add a 'disable' flag? The reasoning behind this is that if the disable flag is set, the model behavior falls back to the default Eloquent/DB behavior (even if the orbit trait is used in the model). This way, you could build your data using the DB and then export it to orbit flat file storage for use through orbit after applying DB transformations (joins, etc.) 

I'm not sure this makes sense but I have a use case for such behavior and if possible, I think it would be a useful addition.

**Comment by ryangjchandler** [comment]
@rgasch I'd recommend using the `DB` facade to get things from the database in this instance, especially if you're just creating flat-files for Orbit to use.

**Comment by rgasch** [comment]
OK, thanks for your speedy reply.
