### ISSUE TITLE
Add one-to-many relationship (and reverse)

### ISSUE THREAD

**Issue by b166er** [ryangjchandler/orbit#72]
would be nice if hasMany() and belongsto() were available in the Model class, like here in docs: https://laravel.com/docs/8.x/eloquent-relationships#one-to-many

**Comment by ryangjchandler** [comment]
@b166er Those methods are still available. We don't change any of the methods.

Here's an example: https://gist.github.com/ryangjchandler/51bb825695f84656731ead0546e6940e

**Comment by b166er** [comment]
thanks, my fault! my migrations script has created database throw docker-instance but with wrong permissions (cache-directory 755 and sqlite-cache-file with 644), i got this exception: "General error: 8 attempt to write a readonly database (SQL: drop table" after googling i found i hint with file permission, after adding more permissions for all files (database+cache) now works. thank you!
