### ISSUE TITLE
Add Query-Builder functionality

### ISSUE THREAD

**Issue by b166er** [ryangjchandler/orbit#73]
would be nice to have Builder for queries in orbit, to do simple queries like: 
`$post = Comment::where('author', 'John')->get();` 
i think it's a simple implementation, just foreach all files in db/directory and search for the matching files.
https://laravel.com/docs/8.x/eloquent#retrieving-models

**Comment by ryangjchandler** [comment]
@b166er You should already be able to do this. Orbital models are just normal Eloquent models so you can do normal queries on them.

**Comment by ryangjchandler** [comment]
My personal blog uses Orbit for content-management, https://github.com/ryangjchandler/ryangjchandler.co.uk.

**Comment by b166er** [comment]
thank you! can you add this example in README of this project as further examples.
