### ISSUE TITLE
Request - Have filenames with padded zeroes?

### ISSUE THREAD

**Issue by mgussekloo** [ryangjchandler/orbit#81]
Hi, thanks for Orbit! 
Is there a way to customize / add padded zeroes to the filenames Orbit creates? This would sort the files better in a code editor that doesn't understand numerical sorting (like Sublime). Curious about your opinion.

**Comment by ryangjchandler** [comment]
@mgussekloo The filename is generated from the primary-key, so you could always change the column it uses or manually override it although I wouldn't recommend the latter.
