### ISSUE TITLE
Truncating OrbitMeta in service provider breaks `shouldRestoreCache` method

### ISSUE THREAD

**Issue by ksassnowski** [ryangjchandler/orbit#99]
The 1.1.0 release adds the following line to the `boot` method of the `OrbitServiceProvider` to truncate the `_orbit_meta` table if it already exists.

https://github.com/ryangjchandler/orbit/pull/95/files#diff-9ab2c0c6607186af00d0a727b04179cd17605199ab1d7662338dd6d7a19ff223R70

Doing so updates the last modified timestamp of the Sqlite database. This introduces a bug in the `shouldRestoreCache` method of the `FileDriver` class since it compares the timestamp of the database file to the last modified timestamp of the content files. This will always return `false` now since the database gets touched at the beginning of each request. This means that the cache never gets updated and we get served stale content until we completely remove the database.

I'm not sure what the best way to fix this is as I didn't look too deeply into the changes in 1.1.0. This might also have slipped through the test suite since the database always gets migrated in tests due to `Orbit::isTesting()` being checked first.

**Comment by ryangjchandler** [comment]
@ksassnowski Excellent spot, this definitely fell through in the test suite. 

I'll take a look at this to figure out the best solution.

**Comment by ryangjchandler** [comment]
You can upgrade to v1.1.1 now. Sorry for introducing this bug in the first place, small oversight on my part!
